export interface Tool {
  id: string;
  name: string;
  description: string;
  route: string;
  icon: string;
  category: string;
  external?: boolean; // If true, opens in new tab
}

export const TOOLS: Tool[] = [
  {
    id: 'js-tokenizer',
    name: 'JS Tokenizers',
    description: 'Tokenize text using various AI tokenizers',
    route: '/tools/js-tokenizer',
    icon: '🤖',
    category: 'AI Tools',
  },
  {
    id: 'rag-chunker',
    name: 'RAG Chunker',
    description: 'Split text into retrieval-friendly chunks with overlap and token counts',
    route: '/tools/rag-chunker',
    icon: '🧩',
    category: 'AI Tools',
  },
  {
    id: 'sentiment-analysis',
    name: 'Sentiment Analysis',
    description: 'Analyze emotional tone of text using AI',
    route: '/tools/sentiment-analysis',
    icon: '😊',
    category: 'AI Tools',
  },
  {
    id: 'zero-shot-classification',
    name: 'Zero-Shot Classification',
    description: 'Classify text into custom categories without training using AI',
    route: '/tools/zero-shot-classification',
    icon: '🎯',
    category: 'AI Tools',
  },
  {
    id: 'sentence-similarity',
    name: 'Sentence Similarity',
    description: 'Generate embeddings and find semantic similarity between texts using AI',
    route: '/tools/sentence-similarity',
    icon: '🔍',
    category: 'AI Tools',
  },
  {
    id: 'question-answering',
    name: 'Question Answering',
    description: 'Answer questions based on provided context using AI',
    route: '/tools/question-answering',
    icon: '❓',
    category: 'AI Tools',
  },
  {
    id: 'fill-mask',
    name: 'Fill-Mask Text Completion',
    description: 'Complete sentences and predict missing words using AI',
    route: '/tools/fill-mask',
    icon: '✨',
    category: 'AI Tools',
  },
  {
    id: 'text-summarization',
    name: 'Text Summarization',
    description: 'Summarize long text into concise overviews using AI',
    route: '/tools/text-summarization',
    icon: '📝',
    category: 'AI Tools',
  },
  {
    id: 'text-extractor',
    name: 'Text Extractor',
    description: 'Extract emails, URLs, IPs, dates, and patterns from text',
    route: '/tools/text-extractor',
    icon: '🔎',
    category: 'AI Tools',
  },
  {
    id: 'json-prettifier',
    name: 'JSON Prettifier',
    description: 'Format and validate JSON data',
    route: '/tools/json-prettifier',
    icon: '{}',
    category: 'Formatting',
  },
  {
    id: 'xml-prettifier',
    name: 'XML Prettifier',
    description: 'Format and validate XML data',
    route: '/tools/xml-prettifier',
    icon: '📄',
    category: 'Formatting',
  },
  {
    id: 'stacktrace-formatter',
    name: 'Stacktrace Formatter',
    description: 'Format and beautify stack traces from multiple programming languages',
    route: '/tools/stacktrace-formatter',
    icon: '📋',
    category: 'Formatting',
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings',
    route: '/tools/base64-encoder',
    icon: '🔤',
    category: 'Formatting',
  },
  {
    id: 'file-size-converter',
    name: 'File Size Converter',
    description: 'Convert file sizes between decimal (SI) and binary (IEC) units',
    route: '/tools/file-size-converter',
    icon: '💾',
    category: 'Formatting',
  },
  {
    id: 'string-similarity',
    name: 'String Similarity',
    description: 'Compare strings using Jaro-Winkler, Levenshtein, Dice, and Hamming algorithms',
    route: '/tools/string-similarity',
    icon: '🔀',
    category: 'Algorithms',
  },
  {
    id: 'ios-app-lookup',
    name: 'iOS App Lookup',
    description: 'Look up iOS app metadata from the App Store using bundle ID',
    route: '/tools/ios-app-lookup',
    icon: '🍎',
    category: 'Apps',
  },
  {
    id: 'terremoto',
    name: 'Terremoto',
    description: 'iOS app for tracking earthquakes in real-time',
    route: 'https://terremoto.developers.do',
    icon: '🌍',
    category: 'Apps',
    external: true,
  },
  {
    id: 'fedpulse',
    name: 'FedPulse',
    description: 'iOS app to search, save, and track federal government jobs',
    route: 'https://fedpulse.developers.do',
    icon: '🏛️',
    category: 'Apps',
    external: true,
  },
  {
    id: 'part107-quiz-prep',
    name: 'FAA Part 107 Quiz Prep',
    description: 'iOS app for FAA Part 107 drone pilot certification exam preparation',
    route: 'https://part107.developers.do',
    icon: '🚁',
    category: 'Apps',
    external: true,
  },
  {
    id: 'citizenship-test-prep',
    name: 'Citizenship Test Prep',
    description: 'iOS app for US citizenship naturalization test preparation',
    route: 'https://citizenshiptest.developers.do',
    icon: '🇺🇸',
    category: 'Apps',
    external: true,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords',
    route: '/tools/password-generator',
    icon: '🔑',
    category: 'Generators',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUIDs (v4)',
    route: '/tools/uuid-generator',
    icon: '🆔',
    category: 'Generators',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs',
    route: '/tools/lorem-ipsum-generator',
    icon: '📄',
    category: 'Generators',
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers and see code samples in multiple languages',
    route: '/tools/random-number-generator',
    icon: '🎲',
    category: 'Generators',
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text, URLs, or any data',
    route: '/tools/qr-code-generator',
    icon: '📱',
    category: 'Generators',
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Convert JSON to TypeScript interfaces',
    route: '/tools/json-to-typescript',
    icon: '📝',
    category: 'Code & Schemas',
  },
  {
    id: 'json-to-jsdoc',
    name: 'JSON to JSDoc',
    description: 'Convert JSON to JSDoc type definitions',
    route: '/tools/json-to-jsdoc',
    icon: '📜',
    category: 'Code & Schemas',
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C#',
    description: 'Convert JSON to C# classes',
    route: '/tools/json-to-csharp',
    icon: '💎',
    category: 'Code & Schemas',
  },
  {
    id: 'json-to-swift',
    name: 'JSON to Swift',
    description: 'Convert JSON to Swift structs',
    route: '/tools/json-to-swift',
    icon: '🍎',
    category: 'Code & Schemas',
  },
  {
    id: 'json-to-kotlin',
    name: 'JSON to Kotlin',
    description: 'Convert JSON to Kotlin data classes',
    route: '/tools/json-to-kotlin',
    icon: '🟣',
    category: 'Code & Schemas',
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go',
    description: 'Convert JSON to Go structs',
    route: '/tools/json-to-go',
    icon: '🐹',
    category: 'Code & Schemas',
  },
  {
    id: 'json-to-rust',
    name: 'JSON to Rust',
    description: 'Convert JSON to Rust structs',
    route: '/tools/json-to-rust',
    icon: '🦀',
    category: 'Code & Schemas',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors and convert between HEX, RGB, HSL, HSV, and CMYK',
    route: '/tools/color-picker',
    icon: '🎨',
    category: 'Code & Schemas',
  },
  {
    id: 'secrets-scanner',
    name: 'Secrets Scanner',
    description: 'Scan text, logs, or configs for leaked keys and tokens',
    route: '/tools/secrets-scanner',
    icon: '🛡️',
    category: 'Security',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT tokens',
    route: '/tools/jwt-decoder',
    icon: '🔓',
    category: 'Security',
  },
  {
    id: 'md5-generator',
    name: 'MD5 Hash',
    description: 'Generate MD5 hashes from text',
    route: '/tools/md5-generator',
    icon: '#️⃣',
    category: 'Security',
  },
  {
    id: 'sha1-generator',
    name: 'SHA-1 Hash',
    description: 'Generate SHA-1 hashes from text',
    route: '/tools/sha1-generator',
    icon: '🔐',
    category: 'Security',
  },
  {
    id: 'sha256-generator',
    name: 'SHA-256/512 Hash',
    description: 'Generate secure SHA-256 or SHA-512 hashes from text',
    route: '/tools/sha256-generator',
    icon: '🔒',
    category: 'Security',
  },
  {
    id: 'clawdbot-security-scanner',
    name: 'Clawdbot Security Scanner',
    description: 'Audit Clawdbot/Moltbot/OpenClaw configs for security vulnerabilities',
    route: '/tools/clawdbot-security-scanner',
    icon: '🤖',
    category: 'Security',
  },
  {
    id: 'saml-decoder',
    name: 'SAML Decoder',
    description: 'Decode SAML Requests/Responses from Base64 to readable XML',
    route: '/tools/saml-decoder',
    icon: '🔏',
    category: 'Security',
  },
  {
    id: 'saml-metadata-parser',
    name: 'SAML Metadata Parser',
    description: 'Parse SAML Metadata XML and extract IdP/SP configuration',
    route: '/tools/saml-metadata-parser',
    icon: '📋',
    category: 'Security',
  },
  {
    id: 'saml-cert-inspector',
    name: 'SAML Certificate Inspector',
    description: 'Inspect X.509 certificates from SAML metadata, responses, or PEM',
    route: '/tools/saml-cert-inspector',
    icon: '📜',
    category: 'Security',
  },
  {
    id: 'saml-builder',
    name: 'SAML Assertion Builder',
    description: 'Generate test SAML Responses, AuthnRequests, and LogoutRequests',
    route: '/tools/saml-builder',
    icon: '🏗️',
    category: 'Security',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Test and view API responses',
    route: '/tools/api-tester',
    icon: '🌐',
    category: 'Networking',
  },
  {
    id: 'oss-data',
    name: 'OSS Data',
    description: 'Open-source data tools for developers',
    route: 'https://data.developers.do',
    icon: '📊',
    category: 'Data',
    external: true,
  },
];
